### ISSUE TITLE
feature request - modbus RTU data through the RS485 input

### ISSUE THREAD

**Issue by abedStatic** [Helmut-Saal/CC100-Node-Red#4]
Hello,

It would be great if we could have a node for directly reading-in modbus RTU data at the onboard RS-485 interface.
Currently trying to connect my [WAGO Power Module](https://www.wago.com/global/current-transformers-and-voltage-taps/3-phase-power-measurement-module/p/2857-570_024-001) to the CC100 and read its values directly in NodeRED.

Thanks.

**Comment by Helmut-Saal** [comment]
THX for the idea, sounds good. If you have a bigger project and need this please contact wago directly to create an feature request for that.
THX again.

**Comment by Ekristoffe** [comment]
Hello @abedStatic,
Have you tried to use this node red modbus node for your case ?

https://github.com/BiancoRoyal/node-red-contrib-modbus

**Comment by Helmut-Saal** [comment]
Take care, in actual Version this is not working completly without fails on CC100!

**Comment by abedStatic** [comment]
hello @Ekristoffe
Yeah, I gave this Palette a try. I got no readings out of it though; maybe I used the wrong settings on the modbus node itself.
Could you maybe share a flow if you've tried it successfully yourself?

**Comment by abedStatic** [comment]
> THX for the idea, sounds good. If you have a bigger project and need this please contact wago directly to create an feature request for that. THX again.

Thanks for the reply.
A specific node is not absolutely neccessary though. Just receiving modbus RTU readings in node red from the onboard RS-485 interface would be sufficient really. Maybe there's a certain buffer file that holds that interface's readings, which we can then read in NodeRED using a docker bind into the container and a "read file" node?
![image](https://user-images.githubusercontent.com/101631897/203120256-4e5cb9b9-3fc5-4fc1-b2ec-811605c0fbcb.png)
I'm not that much experienced with modbus RTU. So please take what I'm suggesting with a grain of salt :)

Thanks.

**Comment by Ekristoffe** [comment]
> hello @Ekristoffe Yeah, I gave this Palette a try. I got no readings out of it though; maybe I used the wrong settings on the modbus node itself. Could you maybe share a flow if you've tried it successfully yourself?

hello, sorry for the long time between reply, after testing with different docker images, i have found that some version of node-red and nodejs could give you a segmentation fault error in the container.

The solution I have found is:

after installing node-red container and the serial node (or the modbus node) but before making the flow,

login in the CC100 with SSH then go to elevated user `su -` then use the command `docker exec -ti --user root <containername> /bin/bash` to open the container console.
(or if you have protainer use it to log in the container console in root)
Then in the container, go to the node-red data folder `cd /data/` and execute the command `npm rebuild --build-from-source`
This will rebuild the serial node from source to the specific of the CC100 system.

Last here is the flow I have used:
```
[
    {
        "id": "f6f2187d.f17ca8",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c616ded647ece222",
        "type": "modbus-read",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": false,
        "showWarnings": true,
        "unitid": "1",
        "dataType": "HoldingRegister",
        "adr": "0",
        "quantity": "16",
        "rate": "10",
        "rateUnit": "s",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "efabea2f2a3c3208",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "emptyMsgOnFail": false,
        "x": 370,
        "y": 420,
        "wires": [
            [
                "75277c029d191dac"
            ],
            [
                "245bdac18308e62f"
            ]
        ]
    },
    {
        "id": "75277c029d191dac",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 1",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 600,
        "y": 420,
        "wires": []
    },
    {
        "id": "245bdac18308e62f",
        "type": "modbus-response",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "registerShowMax": 20,
        "x": 630,
        "y": 460,
        "wires": []
    },
    {
        "id": "a234dfbe6d88148c",
        "type": "modbus-response",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "registerShowMax": 20,
        "x": 630,
        "y": 580,
        "wires": []
    },
    {
        "id": "1f40a5642b8fc10f",
        "type": "modbus-read",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": false,
        "showWarnings": true,
        "unitid": "1",
        "dataType": "HoldingRegister",
        "adr": "136",
        "quantity": "6",
        "rate": "10",
        "rateUnit": "s",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "efabea2f2a3c3208",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "emptyMsgOnFail": false,
        "x": 370,
        "y": 540,
        "wires": [
            [
                "e4a085ce684bd4b0"
            ],
            [
                "a234dfbe6d88148c"
            ]
        ]
    },
    {
        "id": "e4a085ce684bd4b0",
        "type": "debug",
        "z": "f6f2187d.f17ca8",
        "name": "debug 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 600,
        "y": 540,
        "wires": []
    },
    {
        "id": "efabea2f2a3c3208",
        "type": "modbus-client",
        "name": "",
        "clienttype": "serial",
        "bufferCommands": true,
        "stateLogEnabled": false,
        "queueLogEnabled": false,
        "failureLogEnabled": true,
        "tcpHost": "127.0.0.1",
        "tcpPort": "502",
        "tcpType": "DEFAULT",
        "serialPort": "/dev/ttySTM1",
        "serialType": "RTU-BUFFERD",
        "serialBaudrate": "19200",
        "serialDatabits": "8",
        "serialStopbits": "1",
        "serialParity": "even",
        "serialConnectionDelay": "100",
        "serialAsciiResponseStartDelimiter": "0x3A",
        "unit_id": "1",
        "commandDelay": "1",
        "clientTimeout": "1000",
        "reconnectOnTimeout": true,
        "reconnectTimeout": "2000",
        "parallelUnitIdsAllowed": true
    }
]
```
