### ISSUE TITLE
Feature Request - RS485 Modbus RTU

### ISSUE THREAD

**Issue by danielfl313** [Helmut-Saal/CC100-Node-Red#5]
Hallo Herr Saal, wäre es möglich die interne serielle Schnittstelle (X11) des CC100 in Node-Red zu verwenden? Ich würde damit gerne die Wago Modbus Energie-Zähler (REG) abfragen und die Werte verarbeiten.

**Comment by Helmut-Saal** [comment]
Ich paste den Link hier trotzdem noch einmal:

https://youtu.be/Wa1VY3LcqMs
BG
